
[package]
name = "compiler"
version = "0.1.0"
edition = "2021"
default-run = "compiler"

[dependencies]

[[bin]]
name = "render_hir"
path = "src/tools/render_hir.rs"

[[bin]]
name = "render_mir"
path = "src/tools/render_mir.rs"

[profile.dev]
debug = true

[profile.test]
debug = true
